require: rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/TrailingWhitespace: 
  Enabled: false
Style/Documentation: 
  Enabled: false
Style/EmptyMethod: 
  Enabled: false